### ISSUE TITLE
Swagger specs duplicated with `azure-rest-api-specs` repo.

### ISSUE THREAD

**Issue by IvanGoncharov** [Azure/azure.github.io#22]
Hi @devigned,
I like your list of apis:
https://github.com/Azure/azure.github.io/blob/jekyll/_data/apis.yml
And it sims like ideal place to mark `preferred` or `latest` version of each API as discussed in https://github.com/Azure/azure-rest-api-specs/issues/219

Hower `specs` folder in this repo overlaps with https://github.com/Azure/azure-rest-api-specs
It cause problems for people who use GitHub search, for example, see this [query](https://github.com/search?utf8=%E2%9C%93&q=swagger+SchedulerManagementClient+&type=Code&ref=searchresults).
Moreover, it causing problems for bots crawling Github to extract all Swagger specs.
And I'm not only one who run such bots, for example:
https://sdks.io/Search/FindSDKs?Page=1&Query=&Bridge=Github

If you try to provide Swagger specs with CORS support.
Please consider hosting them in [gh-pages](https://help.github.com/articles/user-organization-and-project-pages/#project-pages) branch of `azure-rest-api-specs` repo.
As a bonus feature, you can configure CI to automatically do deploy on `gh-pages`.
I use exactly the same approach for my catalog, I even wrote script to do deployment from Travis:
https://www.npmjs.com/package/deploy-to-gh-pages

**Comment by devigned** [comment]
Interesting -- great idea!. I'll take a look at the gh-pages solution to my issue with CORS.

**Comment by IvanGoncharov** [comment]
@devigned For more than a year I work on this topic(Swagger catalog).
So I solved a number of technical problems.

But at the same time, I'm lacking feedback from API owners.
I would love to hear your feedback/ideas and answer your questions.
If you will have 10-15 min, we can schedule a call at Skype(ivangon4arov) or Hangouts(ivan.goncharov.ua@gmail.com).
Just pick any time that suits you best.

**Comment by devigned** [comment]
I'll leave this open with the intent of moving to a gh-pages approach, but I don't think it will get closed out very soon. There are other things in my queue prior to getting this done.

Thank you for the feedback and when I get back to this, I'll reach out.

**Comment by IvanGoncharov** [comment]
@devigned Cool.
By the way, I added all Azure public APIs into my catalog.
And you can use it will all integrations: https://github.com/APIs-guru/api-models#existing-integrations
