### ISSUE TITLE
CLA Information inaccurate. 

### ISSUE THREAD

**Issue by hdost** [Azure/azure.github.io#58]
https://github.com/Azure/azure-sdk-for-python/issues/2950 as reference.

**Comment by jeffwilcox** [comment]
This site is outdated at this point, the Python SDK should likely be updated with more recent information about the Microsoft-wide CLA system that is in place.

Recommend closing this issue as the `azure.github.io` pages will not be around much longer.

**Comment by hdost** [comment]
@jeffwilcox what is the replacement for azure.github.io? Where can I go to see this new CLA process?

**Comment by jeffwilcox** [comment]
https://cla.microsoft.com
